<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Accounts\DTOs\Responses\**" />
    <Compile Remove="Common\DTOs\Requests\**" />
    <Compile Remove="Mappings\**" />
    <EmbeddedResource Remove="Accounts\DTOs\Responses\**" />
    <EmbeddedResource Remove="Common\DTOs\Requests\**" />
    <EmbeddedResource Remove="Mappings\**" />
    <None Remove="Accounts\DTOs\Responses\**" />
    <None Remove="Common\DTOs\Requests\**" />
    <None Remove="Mappings\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Scrutor" />
    <PackageReference Include="SharpGrip.FluentValidation.AutoValidation.Mvc" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\cafedebug-backend.infrastructure\cafedebug-backend.infrastructure.csproj" />
    <ProjectReference Include="..\cafedebug-backend.domain\cafedebug-backend.domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Podcasts\Validators\Category\" />
  </ItemGroup>

</Project>
